import type { InboxItem } from "@/types/email";

const now = Math.floor(Date.now() / 1000);
const mins = (n: number) => now - n * 60;
const hrs = (n: number) => now - n * 3600;
const days = (n: number) => now - n * 86400;

export const MOCK_INBOX_ITEMS: InboxItem[] = [
  {
    message: {
      id: 1,
      account_id: 1,
      folder_id: 1,
      uid: 1001,
      from_addr: "ceo@acmecorp.com",
      from_name: "Sarah Chen",
      to_addrs: '["you@example.com"]',
      subject: "Q3 board deck — please review before Thursday",
      date: mins(18),
      snippet:
        "Hi, can you take a look at the deck before the board meeting on Thursday? I need your sign-off on the revenue slide.",
      body_text:
        "Hi,\n\nCan you take a look at the attached deck before the board meeting on Thursday? I need your sign-off on the revenue slide in particular. The numbers look right but I want a second pair of eyes.\n\nThanks,\nSarah",
      has_attachments: 1,
      created_at: mins(18),
    },
    enrichment: {
      message_id: 1,
      category: "urgent",
      priority: 92,
      summary: "CEO needs deck review before Thursday board meeting — revenue slide sign-off required.",
      facts: ["Board meeting is Thursday", "Deck attached", "Revenue slide needs approval"],
      is_actionable: true,
      needs_response: true,
      task_count: 1,
    },
  },
  {
    message: {
      id: 2,
      account_id: 1,
      folder_id: 1,
      uid: 1002,
      from_addr: "hr@yourcompany.com",
      from_name: "People Team",
      to_addrs: '["you@example.com"]',
      subject: "Your PTO request for June 3–7 has been approved",
      date: hrs(2),
      snippet: "Great news — your time-off request for June 3 to 7 has been approved by your manager.",
      body_text:
        "Hi,\n\nGreat news — your time-off request for June 3–7 has been approved by your manager.\n\nPlease make sure to update the team calendar and set an out-of-office reply before you leave.\n\nBest,\nPeople Team",
      has_attachments: 0,
      created_at: hrs(2),
    },
    enrichment: {
      message_id: 2,
      category: "work",
      priority: 35,
      summary: "PTO for June 3–7 approved. Reminder to update team calendar and set OOO reply.",
      facts: ["PTO approved for June 3–7", "Set OOO reminder"],
      is_actionable: true,
      needs_response: false,
      task_count: 0,
    },
  },
  {
    message: {
      id: 3,
      account_id: 1,
      folder_id: 1,
      uid: 1003,
      from_addr: "noreply@github.com",
      from_name: "GitHub",
      to_addrs: '["you@example.com"]',
      subject: "[retposto/retposto] PR #42: feat: inbox view scaffold",
      date: hrs(3),
      snippet: "0xNullAI opened a pull request: feat: inbox view scaffold. 12 files changed.",
      body_text:
        "0xNullAI opened pull request #42 in retposto/retposto\n\nfeat: inbox view scaffold\n12 files changed, +847, -3\n\nView pull request: https://github.com/retposto/retposto/pull/42",
      has_attachments: 0,
      created_at: hrs(3),
    },
    enrichment: {
      message_id: 3,
      category: "work",
      priority: 55,
      summary: "New PR #42 opened: inbox view scaffold — 12 files changed.",
      facts: ["PR #42 opened by 0xNullAI", "12 files changed"],
      is_actionable: true,
      needs_response: false,
      task_count: 0,
    },
  },
  {
    message: {
      id: 4,
      account_id: 1,
      folder_id: 1,
      uid: 1004,
      from_addr: "alex@friend.me",
      from_name: "Alex Rivera",
      to_addrs: '["you@example.com"]',
      subject: "Hiking trip this weekend?",
      date: hrs(5),
      snippet: "Hey! A few of us are planning a trail hike Saturday morning. You in?",
      body_text:
        "Hey!\n\nA few of us are planning a trail hike Saturday morning — Marin Headlands, starts at 8am. You in? Let me know by Thursday so we can figure out carpools.\n\nCheers,\nAlex",
      has_attachments: 0,
      created_at: hrs(5),
    },
    enrichment: {
      message_id: 4,
      category: "personal",
      priority: 48,
      summary: "Alex invites you to a Saturday morning hike — reply needed by Thursday for carpools.",
      facts: ["Hike: Saturday 8am, Marin Headlands", "RSVP by Thursday"],
      is_actionable: true,
      needs_response: true,
      task_count: 1,
    },
  },
  {
    message: {
      id: 5,
      account_id: 1,
      folder_id: 1,
      uid: 1005,
      from_addr: "noreply@stripe.com",
      from_name: "Stripe",
      to_addrs: '["you@example.com"]',
      subject: "Receipt for your payment of $49.00",
      date: hrs(8),
      snippet: "Your payment of $49.00 to Vercel Inc was successfully processed.",
      body_text:
        "Receipt\n\nAmount: $49.00\nMerchant: Vercel Inc\nDate: May 21, 2026\nPayment method: Visa •••• 4242\n\nThank you for your payment.",
      has_attachments: 0,
      created_at: hrs(8),
    },
    enrichment: {
      message_id: 5,
      category: "transactional",
      priority: 20,
      summary: "$49.00 payment to Vercel processed successfully via Stripe.",
      facts: ["Payment: $49.00 to Vercel", "Card: Visa ••4242"],
      is_actionable: false,
      needs_response: false,
      task_count: 0,
    },
  },
  {
    message: {
      id: 6,
      account_id: 1,
      folder_id: 1,
      uid: 1006,
      from_addr: "security-noreply@apple.com",
      from_name: "Apple",
      to_addrs: '["you@example.com"]',
      subject: "Your Apple ID was used to sign in on a new device",
      date: hrs(10),
      snippet:
        "Your Apple ID was used to sign in to a new MacBook Pro. If this was you, you can ignore this email.",
      body_text:
        "Your Apple ID (leonardoshen@icloud.com) was used to sign in on a new MacBook Pro.\n\nIf this was you, no action is needed.\n\nIf you did not sign in, your account may be compromised. Visit appleid.apple.com immediately.",
      has_attachments: 0,
      created_at: hrs(10),
    },
    enrichment: {
      message_id: 6,
      category: "urgent",
      priority: 85,
      summary: "Apple ID sign-in detected on new MacBook Pro — verify if it was you.",
      facts: ["New device sign-in detected", "Action needed if unrecognized"],
      is_actionable: true,
      needs_response: false,
      task_count: 0,
    },
  },
  {
    message: {
      id: 7,
      account_id: 1,
      folder_id: 1,
      uid: 1007,
      from_addr: "digest@tldr.tech",
      from_name: "TLDR Tech",
      to_addrs: '["you@example.com"]',
      subject: "TLDR 2026-05-21: Apple's new AI chip, Rust 2.0 ships",
      date: hrs(12),
      snippet:
        "Today's top stories: Apple unveils M5 with dedicated AI cores, Rust 2.0 released with async traits stable...",
      body_text:
        "TLDR Tech — May 21, 2026\n\n• Apple unveils M5 chip with 40-core Neural Engine\n• Rust 2.0 ships with stable async traits and improved borrow checker\n• OpenAI launches GPT-5 with 1M token context window\n• New EU AI Act enforcement begins Q3 2026\n\nUnsubscribe | View in browser",
      has_attachments: 0,
      created_at: hrs(12),
    },
    enrichment: {
      message_id: 7,
      category: "newsletter",
      priority: 15,
      summary: "Tech digest: Apple M5 chip, Rust 2.0, GPT-5 announcement, EU AI Act update.",
      is_actionable: false,
      needs_response: false,
      task_count: 0,
    },
  },
  {
    message: {
      id: 8,
      account_id: 1,
      folder_id: 1,
      uid: 1008,
      from_addr: "team@linear.app",
      from_name: "Linear",
      to_addrs: '["you@example.com"]',
      subject: "Jordan Kim assigned you 3 issues",
      date: days(1),
      snippet: "Jordan Kim assigned: [RET-88] Fix sync deadlock, [RET-89] Add rate limiting, [RET-90] Write API docs.",
      body_text:
        "Jordan Kim assigned you 3 issues:\n\n• [RET-88] Fix sync deadlock (Priority: Urgent)\n• [RET-89] Add rate limiting to IMAP client (Priority: High)\n• [RET-90] Write API documentation (Priority: Medium)\n\nView in Linear",
      has_attachments: 0,
      created_at: days(1),
    },
    enrichment: {
      message_id: 8,
      category: "work",
      priority: 75,
      summary: "3 new Linear issues assigned by Jordan Kim — includes urgent sync deadlock fix.",
      facts: ["RET-88: sync deadlock (Urgent)", "RET-89: rate limiting", "RET-90: API docs"],
      is_actionable: true,
      needs_response: false,
      task_count: 3,
    },
  },
  {
    message: {
      id: 9,
      account_id: 1,
      folder_id: 1,
      uid: 1009,
      from_addr: "weekly@substack.com",
      from_name: "The Pragmatic Engineer",
      to_addrs: '["you@example.com"]',
      subject: "How Big Tech engineers actually work",
      date: days(1),
      snippet:
        "This week: an inside look at how engineers at Google, Meta, and Apple approach large-scale system design...",
      body_text:
        "The Pragmatic Engineer — May 20, 2026\n\nHow Big Tech engineers actually work\n\nThis week I interviewed 8 engineers across Google, Meta, and Apple about their actual day-to-day...\n\n[Read more on Substack]",
      has_attachments: 0,
      created_at: days(1),
    },
    enrichment: {
      message_id: 9,
      category: "newsletter",
      priority: 12,
      summary: "Pragmatic Engineer: inside look at how Big Tech engineers approach large-scale system design.",
      is_actionable: false,
      needs_response: false,
      task_count: 0,
    },
  },
  {
    message: {
      id: 10,
      account_id: 1,
      folder_id: 1,
      uid: 1010,
      from_addr: "mom@family.net",
      from_name: "Mom",
      to_addrs: '["you@example.com"]',
      subject: "Dad's birthday dinner — Sunday the 25th",
      date: days(2),
      snippet: "Hi honey, we're planning a small dinner for Dad's birthday on Sunday. Can you make it?",
      body_text:
        "Hi honey,\n\nWe're planning a small dinner for Dad's birthday on Sunday the 25th, around 6pm. It'll just be family and a couple of close friends.\n\nCan you make it? Let me know so I can plan the food!\n\nLove,\nMom",
      has_attachments: 0,
      created_at: days(2),
    },
    enrichment: {
      message_id: 10,
      category: "personal",
      priority: 60,
      summary: "Mom asking if you can attend Dad's birthday dinner Sunday May 25th at 6pm.",
      facts: ["Dinner: Sunday May 25, 6pm", "Family + close friends"],
      is_actionable: true,
      needs_response: true,
      task_count: 1,
    },
  },
  {
    message: {
      id: 11,
      account_id: 1,
      folder_id: 1,
      uid: 1011,
      from_addr: "noreply@amazon.com",
      from_name: "Amazon",
      to_addrs: '["you@example.com"]',
      subject: "Your order has shipped — arrives Thursday",
      date: days(2),
      snippet: "Order #112-3456789-0123456: USB-C hub (4-port) has shipped and will arrive Thursday by 8pm.",
      body_text:
        "Your order has shipped!\n\nOrder: #112-3456789-0123456\nItem: Anker 4-Port USB-C Hub\nEstimated delivery: Thursday, May 23 by 8:00 PM\n\nTrack your package",
      has_attachments: 0,
      created_at: days(2),
    },
    enrichment: {
      message_id: 11,
      category: "transactional",
      priority: 18,
      summary: "Amazon order #112-3456789 shipped — USB-C hub arrives Thursday May 23 by 8pm.",
      is_actionable: false,
      needs_response: false,
      task_count: 0,
    },
  },
  {
    message: {
      id: 12,
      account_id: 1,
      folder_id: 1,
      uid: 1012,
      from_addr: "notifications@twitter.com",
      from_name: "X (Twitter)",
      to_addrs: '["you@example.com"]',
      subject: "You have 14 new notifications",
      date: days(3),
      snippet: "@rustlang retweeted your post. @ThePrimeagen and 12 others liked your thread.",
      body_text:
        "You have 14 new notifications on X.\n\n@rustlang retweeted your post about async Rust.\n@ThePrimeagen liked your thread.\n12 others liked and replied to your posts.\n\nView your notifications",
      has_attachments: 0,
      created_at: days(3),
    },
    enrichment: {
      message_id: 12,
      category: "social",
      priority: 10,
      summary: "14 X notifications — @rustlang retweeted your post; @ThePrimeagen liked your thread.",
      is_actionable: false,
      needs_response: false,
      task_count: 0,
    },
  },
  {
    message: {
      id: 13,
      account_id: 1,
      folder_id: 1,
      uid: 1013,
      from_addr: "deals@acmeshop.com",
      from_name: "ACME Shop",
      to_addrs: '["you@example.com"]',
      subject: "Flash sale: 50% off everything today only!!!",
      date: days(4),
      snippet: "Huge savings await! Don't miss our biggest sale of the year. Click now before it's too late.",
      body_text:
        "HUGE FLASH SALE\n50% OFF EVERYTHING — TODAY ONLY\n\nDon't miss out! Shop now before stocks run out.\nUse code: FLASH50\n\nUnsubscribe | This email was sent to you because you signed up for promotional emails.",
      has_attachments: 0,
      created_at: days(4),
    },
    enrichment: {
      message_id: 13,
      category: "spam",
      priority: 2,
      summary: "Promotional spam: 50% off flash sale from ACME Shop.",
      is_actionable: false,
      needs_response: false,
      task_count: 0,
    },
  },
  {
    message: {
      id: 14,
      account_id: 1,
      folder_id: 1,
      uid: 1014,
      from_addr: "newsletter@bytebytego.com",
      from_name: "ByteByteGo",
      to_addrs: '["you@example.com"]',
      subject: "System Design: How does Kafka scale to millions of messages/sec?",
      date: days(5),
      snippet:
        "In this issue: a deep dive into Kafka's partition model, consumer groups, and replication strategy.",
      body_text:
        "ByteByteGo Newsletter — May 16, 2026\n\nHow does Kafka scale to millions of messages per second?\n\nKafka's secret is its partition model: each topic is split into partitions distributed across brokers...\n\n[Read the full article]",
      has_attachments: 0,
      created_at: days(5),
    },
    enrichment: {
      message_id: 14,
      category: "newsletter",
      priority: 14,
      summary: "ByteByteGo deep dive: Kafka's partition model, consumer groups, and replication for scale.",
      is_actionable: false,
      needs_response: false,
      task_count: 0,
    },
  },
];

/**
 * Returns mock items optionally filtered by category.
 * The actual filtering logic lives in InboxList; this is the raw data source.
 */
export function getMockItems(): InboxItem[] {
  return MOCK_INBOX_ITEMS;
}
